### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by sergiycheck** [sergiycheck/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by sergTesst** [comment]
Highly skilled and experienced software engineer effectively developing solutions for fintech: payment systems, crypto software, trading engines, exchanges, smart contracts, etc; for media processing & natural language processing; for e-commerce. Familiar with the highload fault-tolerant enterprise systems & code optimization. Able to solve non-standard tasks requiring a scientific approach. Advanced UI/UX designer skills

    субота, 2 травня 2020 р., 17:58:26 GMT+3, Serhii <notifications@github.com> написав:  
 
 


Assigned #5 to @sergTesst.
